output_dir: /results/of_2d
encryption_key: nvidia_tao
model_config:
  model_type: of
  backbone: resnet18
  of_seq_length: 10
train_config:
  optim:
    lr: 0.01
    momentum: 0.9
  epochs: 20
dataset_config:
  train_dataset_dir: /data/train
  val_dataset_dir: /data/test
  label_map:
    walk: 0
    sits: 1
    squa: 2
    fall: 3
    bend: 4
  output_shape:
  - 224
  - 224
  batch_size: 32
  workers: 8
