evaluate:
  num_gpus: 1
  conf_threshold: 0.0
  input_width: 960
  input_height: 544
dataset:
  test_data_sources:
    image_dir: "???"
    json_file: "???"
  num_classes: 91
  batch_size: 8
  workers: 8
  augmentation:
    fixed_padding: False
model:
  backbone: resnet_50
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  num_select: 100
  dropout_ratio: 0.0
  dim_feedforward: 2048