results_dir: /tao-pt/2tasks_bigdatasetgan_gastro_tmp

encryption_key: tlt_encode
task: bigdatasetgan
train:
  resume_training_checkpoint_path: null
  pretrained_model_path: null
  num_epochs: 3000
  num_nodes: 1
  num_gpus: 1
  # gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  deterministic_all: True
  validation_interval: 1
  checkpoint_interval: 1
  # stylegan:
  #   gan_seed_offset: 0  # Try when encountering GAN mode collapsed
  #   optim_generator:
  #     lr: 0.0025
  #     optim: "Adam"
  #     betas: [0, 0.99]
  #     eps: 1e-08
  #   optim_discriminator:
  #     lr: 0.002
  #     optim: "Adam"
  #     betas: [0, 0.99]
  #     eps: 1e-08
  bigdatasetgan:
    optim_labeller:
      lr: 4e-3
      optim: "AdamW"
      betas: [0.9, 0.95]
  results_dir: "${results_dir}/train"
  tensorboard:
    enabled: True
    infrequent_logging_frequency: 1

model:
  input_embeddings_path: null
  generator:
    backbone: "stylegan3-t"
    superres: True
    added_head_superres: # Ignore this sub section when the superres == False
      head_layers: [4, 4, 4, 4, 4]
      up_factor: [2, 2, 2, 2, 2]
      # pretrained_stem_path: null # BigDatasetGAN does not require stem checkpoint
      reinit_stem_anyway: False
    stem: 
      fp32: False
      cbase: 16384
      cmax: 256
      syn_layers: 7
      resolution: 16
  stylegan:
    loss:
      cls_weight: 0.0
    discriminator:
      backbones: ["deit_base_distilled_patch16_224", "tf_efficientnet_lite0"]
    metrics:
      inception_fid_path: null
  bigdatasetgan:
    feature_extractor:
      stylegan_checkpoint_path: /tao-pt/gastro_from16_to32_to64_to128_to256_to512/trained_ngc/model_epoch_1099.pth
      blocks: [2, 6, 11, 15]

dataset:
  common:
    cond: True
    num_classes: 6 # Be 0 when cond==False
    img_channels: 3
    img_resolution: 512
  # stylegan:
  #   train_dataset:
  #     images_dir: /dataset/hyperkvasir_16/hyperkvasir_16_class.zip
  #     # images_dir: /dataset/hyperkvasir_512/hyperkvasir_512.zip
  #   validation_dataset:
  #     images_dir: /dataset/hyperkvasir_16/hyperkvasir_16_class.zip
  #     # images_dir: /dataset/hyperkvasir_512/hyperkvasir_512.zip
  #   test_dataset:
  #     images_dir: /dataset/hyperkvasir_16/hyperkvasir_16_class.zip
  #     # images_dir: /dataset/hyperkvasir_512/hyperkvasir_512.zip
  #   infer_dataset:
  #     start_seed: 0
  #     end_seed: 50
  #   mirror: True
  bigdatasetgan:
    train_dataset:
      images_dir: /out_labeled/train/masks
    validation_dataset:
      images_dir: /out_labeled/train/masks
    test_dataset:
      images_dir: /out_labeled/train/masks
  batch_size: 16
  workers: 3

evaluate: 
  num_nodes: 1
  num_gpus: 1
  # gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  checkpoint: "/tao-pt/2tasks_stylegan_gastro_tmp/train/model_epoch_007.pth"

inference:
  num_nodes: 1
  num_gpus: 1
  # gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  checkpoint: "/tao-pt/2tasks_stylegan_gastro_tmp/train/model_epoch_007.pth"
  truncation_psi: 1.0
  translate: [0.0, 0.0]
  rotate: 0.0
  centroids_path: null
  class_idx: 2

export:
  gpu_id: 0
  checkpoint: "/tao-pt/2tasks_stylegan_gastro_tmp/train/model_epoch_007.pth"
  onnx_file: "${results_dir}/bigdatasetgan/bigdatasetgan.onnx"
  batch_size: -1
  opset_version: 17
  onnxruntime:
    test_onnxruntime: True
    sample_result_dir: "${results_dir}/bigdatasetgan"
    runtime_seed: 0
    runtime_batch_size: 2
    runtime_class_dix: 2