results_dir:  ???
export:
  gpu_id: 0
  checkpoint:  ???
  onnx_file:  ???
  input_width: 960
  input_height: 544
  opset_version: 17
  batch_size: -1
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dim_feedforward: 2048
  aux_loss: False