encryption_key: "???"
results_dir: "???"
inference:
  num_gpus: 1
  checkpoint: "???"
  conf_threshold: 0.5
  input_width: 960
  input_height: 544
  color_map:
    person: green
    face: red
dataset:
  infer_data_sources:
    image_dir: "???"
    classmap: "???"
  num_classes: 91
  batch_size: 8
  workers: 8
model:
  backbone: resnet_50
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True
  dropout_ratio: 0.3