results_dir: "???"
train:
  num_gpus: 1
  num_nodes: 1
  validation_interval: 1
  optim:
    lr_backbone: 1e-05
    lr: 0.0001
    lr_steps: [10, 20, 30, 40]
    momentum: 0.9
  num_epochs: 50
dataset:
  train_sampler: default_sampler
  train_data_sources:
    - image_dir: "???"
      json_file: "???"
  val_data_sources:
    - image_dir: "???"
      json_file: "???"
  num_classes: 91
  batch_size: 2
  workers: 8
model:
  pretrained_backbone_path: "???"
  backbone: resnet_50
  train_backbone: True
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True
  dropout_ratio: 0.3
