results_dir: "???"
encryption_key: nvidia_tao
model:
  model_type: ST-GCN
  pretrained_model_path: ""
  input_channels: 3
  dropout: 0.5
  graph_layout: "nvidia"
  graph_strategy: "spatial"
  edge_importance_weighting: True
dataset:
  train_dataset:
    data_path: "???"
    label_path: "???"
  val_dataset:
    data_path: "???"
    label_path: "???"
  num_classes: 6
  label_map:
    sitting_down: 0
    getting_up: 1
    sitting: 2
    standing: 3
    walking: 4
    jumping: 5
  batch_size: 16
  num_workers: 1
train:
  results_dir: "${results_dir}/train"
  optim:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    lr_scheduler: "MultiStep"
    lr_steps:
    - 10
    - 60
    lr_decay: 0.1
  num_epochs: 70
  checkpoint_interval: 5
inference:
  results_dir: "${results_dir}/inference"
  checkpoint: "???"
  output_file: "???"
  test_dataset:
    data_path: "???"
evaluate:
  results_dir: "${results_dir}/evaluate"
  checkpoint: "???"
  test_dataset:
    data_path: "???"
    label_path: "???"
export:
  results_dir: "${results_dir}/export"
  checkpoint: "???"
dataset_convert:
  results_dir: "${results_dir}/dataset_convert"
  data: "???"
  pose_type: "3dbp"
  num_joints: 34
  input_width: 1920
  input_height: 1080
  focal_length: 1200.0
  sequence_length_max: 300
  sequence_length_min: 10
  sequence_length: 100
  sequence_overlap: 0.5
