results_dir: /results

evaluate:
  num_gpus: 1
  checkpoint: "???"
  opencv: False
  eval_num_symmetry: 1
  results_dir: /results

dataset:
  test_data: /data/bike/val
  num_classes: 1
  batch_size: 4
  workers: 4

model:
  down_ratio: 4
  backbone:
    model_type: fan_small
