encryption_key: "???"
results_dir: "???"

dataset:
  inference_data: "???"
  num_classes: 1
  batch_size: 4
  workers: 4

inference:
  checkpoint: "???"
  visualization_threshold: 0.3
  principle_point_x: 300.77100118001306
  principle_point_y: 392.8848775227865
  focal_length_x: 615.0476582845052
  focal_length_y: 615.0476582845052
  skew: 0.0
  use_pnp: True
  save_json: True
  save_visualization: True
  opencv: True

model:
  down_ratio: 4
  backbone:
    model_type: "???"
