results_dir: /results

dataset:
  train_data: /data/bike/train
  val_data: /data/bike/val
  num_classes: 1
  batch_size: 32
  workers: 8
  category: "bike"
  num_symmetry: 1
  max_objs: 10

train:
  num_gpus: 1
  validation_interval: 20
  checkpoint_interval: ${train.validation_interval}
  num_epochs: 40
  clip_grad_val: 100.0
  seed: 317
  resume_training_checkpoint_path: null
  precision: "fp32"

  optim:
    lr: 6e-05
    lr_steps: [90, 120]

model:
  down_ratio: 4
  use_pretrained: True
  backbone:
    model_type: fan_small
    pretrained_backbone_path: /results/pretrained_models/pretrained_fan_classification_nvimagenet_vfan_small_hybrid_nvimagenet/fan_small_hybrid_nvimagenet.pth
