results_dir: "???"

dataset:
  train_data: "???"
  val_data: "???"
  num_classes: 1
  batch_size: 64
  workers: 4
  category: "???"
  num_symmetry: 1
  max_objs: 10

train:
  num_gpus: 1
  validation_interval: 20
  checkpoint_interval: ${train.validation_interval}
  num_epochs: 140
  clip_grad_val: 100.0
  randomseed: 317
  resume_training_checkpoint_path: null
  precision: "fp32"

  optim:
    lr: 6e-05
    lr_steps: [90, 120]

model:
  down_ratio: 4
  use_pretrained: False
  backbone:
    model_type: "???"
    pretrained_backbone_path: null
