results_dir: ???

evaluate:
  checkpoint: ???

dataset:
  data:
    samples_per_gpu: 512
    workers_per_gpu: 8
    train:
      data_prefix: ???
      pipeline: # Augmentations alone
        - type: RandomResizedCrop
          size: 224
        - type: RandomFlip
          flip_prob: 0.5
          direction: "horizontal"
        - type: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
    val:
      data_prefix: ???
    test:
      data_prefix: ???

model:
  backbone:
    type: "vit_large_patch14_dinov2_swiglu"
    freeze: true
    pretrained: ???
  init_cfg:
    checkpoint: ???
  head:
    type: LinearClsHead
    num_classes: 1000
    in_channels: 1024
    loss:
      type: CrossEntropyLoss
      loss_weight: 1.0
      use_soft: False
    topk: [1, 5]

train:
  train_config:
    find_unused_parameters: True
    optimizer:
      type: AdamW
      lr: 1e-3
    lr_config:
      policy: CosineAnnealing
      min_lr: 5e-6
      warmup: 'linear'
      warmup_iters: 10
      warmup_by_epoch: False
    optimizer_config:
      grad_clip:
        max_norm: 5.0
    runner:
      max_epochs: 10
    checkpoint_config:
      interval: 1
    logging:
      interval: 50
    validate: True
    evaluation:
      interval: 1
