results_dir: ???
dataset:
  data:
    samples_per_gpu: 128
    workers_per_gpu: 8
    train:
      data_prefix: ???
      pipeline:
        - type: LoadImageFromFile
        - type: RandomResizedCrop
          size: 224
        - type: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        - type: RandomFlip
          flip_prob: 0.5
          direction: "horizontal"
    val:
      data_prefix: ???
    test:
      data_prefix: ???
model:
  backbone:
    type: faster_vit_0_224
  head:
    type: LinearClsHead
    num_classes: 1000
    loss:
      type: CrossEntropyLoss
      loss_weight: 1.0
      use_soft: True
    topk: [1, 5]
  train_cfg:
    augments:
      - type: BatchMixup
        alpha: 0.8
        num_classes: 1000
        prob: 0.5
      - type: BatchCutMix
        alpha: 1.0
        num_classes: 1000
        prob: 0.5
train:
  train_config:
    find_unused_parameters: True
    optimizer:
      type: AdamW
      lr: 0.005
      weight_decay: 0.05
    lr_config:
      policy: CosineAnnealingCooldown
      min_lr: 5e-6
      cool_down_time: 10
      warmup: 'linear'
      warmup_iters: 20
      warmup_by_epoch: True
    optimizer_config:
      grad_clip:
        max_norm: 5.0
    runner:
      max_epochs: 310
    checkpoint_config:
      interval: 1
    logging:
      interval: 500
    validate: True
    evaluation:
      interval: 1
    custom_hooks:
      - type: "EMAHook"
        momentum: 0.0002
        priority: "ABOVE_NORMAL"