results_dir: ???
dataset:
  data:
    samples_per_gpu: 512
    workers_per_gpu: 8
    train:
      data_prefix: ???
      pipeline: # Augmentations alone
        - type: RandomResizedCrop
          scale: 224
        - type: RandomFlip
          prob: 0.5
          direction: "horizontal"
        - type: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
    val:
      data_prefix: ???
    test:
      data_prefix: ???
train:
  exp_config:
    manual_seed: 49
  train_config:
    runner:
      max_epochs: 40
    checkpoint_config:
      interval: 1
    logging:
      interval: 500
    evaluation:
      interval: 5
    optimizer:
      type: 'AdamW'
      lr: 10e-6


model:
  backbone:
    type: "open_clip"
    custom_args:
      model_name: "ViT-B-32"
    freeze: False
    pretrained: ???
  head:
    type: "TAOLinearClsHead"
    num_classes: 2
    custom_args:
      head_init_scale: 1
    loss:
      type: LabelSmoothLoss
      label_smooth_val: 0.1
      mode: 'original'

  
