# Training with the following spec can reproduce reported accuracy of 79.3
results_dir: ???
dataset:
  data:
    samples_per_gpu: 128
    workers_per_gpu: 8
    train:
      data_prefix: ???
      pipeline:
        - type: LoadImageFromFile
        - type: RandomResizedCrop
          scale: 224
        - type: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        - type: RandomFlip
          prob: 0.5
          direction: "horizontal"
    val:
      data_prefix: ???
    test:
      data_prefix: ???
model:
  backbone:
    type: gc_vit_xxtiny
    custom_args:
      use_rel_pos_bias: True
  head:
    type: TAOLinearClsHead
    num_classes: 1000
    loss:
      type: CrossEntropyLoss
      loss_weight: 1.0
      use_soft: True
    topk: [1, 5]
  train_cfg:
    augments:
      - type: Mixup
        alpha: 0.8
      - type: CutMix
        alpha: 1.0
train:
  train_config:
    find_unused_parameters: True
    optimizer:
      type: AdamW
      lr: 0.005
      weight_decay: 0.05
   lr_config:
      type: CosineAnnealingLR
      T_max: 200
      by_epoch: True
      begin: 0
    optimizer_config:
      grad_clip:
        max_norm: 5.0
    runner:
      max_epochs: 310
    checkpoint_config:
      interval: 1
    logging:
      interval: 500
    validate: True
    evaluation:
      interval: 1
    custom_hooks:
      - type: "EMAHook"
        momentum: 0.0002
        priority: "ABOVE_NORMAL"