output_dir: "??"
encryption_key: nvidia_tao
seed: 1111
gpu_ids: [0]
resume_training_checkpoint_path: "??"
# pretrained_model_path:
model_config:
  TPS: False
  backbone: ResNet
  feature_channel: 512
  sequence: BiLSTM
  hidden_size: 256
  prediction: CTC
train_config:
  optim:
    name: "adadelta"
    lr: 1.0
  clip_grad_norm: 5.0
  epochs: 12
  checkpoint_interval: 1
  validation_interval: 1
dataset_config:
  train_dataset_dir: ["??"]
  val_dataset_dir: "??"
  character_list_file: "??"
  img_width: 100
  img_height: 32
  img_channel: 1
  max_label_length: 25
  batch_size: 32
  workers: 4
  augmentation_config:
    keep_aspect_ratio: False
