results_dir: "???"
encryption_key: nvidia_tao
model:
  backbone: resnet_50
  last_stride: 1
  pretrain_choice: imagenet
  pretrained_model_path: "???"
  input_channels: 3
  input_width: 128
  input_height: 256
  neck: bnneck
  feat_dim: 256
  neck_feat: after
  metric_loss_type: triplet
  with_center_loss: False
  with_flip_feature: False
  label_smooth: True
dataset:
  train_dataset_dir: "???"
  test_dataset_dir: "???"
  query_dataset_dir: "???"
  num_classes: 751
  batch_size: 64
  val_batch_size: 128
  num_workers: 8
  pixel_mean: [0.485, 0.456, 0.406]
  pixel_std: [0.226, 0.226, 0.226]
  padding: 10
  prob: 0.5
  re_prob: 0.5
  sampler: softmax_triplet
  num_instances: 4
re_ranking:
  re_ranking: True
  k1: 20
  k2: 6
  lambda_value: 0.3
train:
  results_dir: "${results_dir}/train"
  optim:
    name: Adam
    steps: [40, 70]
    gamma: 0.1
    bias_lr_factor: 1
    weight_decay: 0.0005
    weight_decay_bias: 0.0005
    warmup_factor: 0.01
    warmup_iters: 10
    warmup_method: linear
    base_lr: 0.00035
    momentum: 0.9
    center_loss_weight: 0.0005
    center_lr: 0.5
    triplet_loss_margin: 0.3
  num_epochs: 120
  checkpoint_interval: 10
inference:
  results_dir: "${results_dir}/inference"
  checkpoint: "???"
  output_file: "???"
  test_dataset: "???"
  query_dataset: "???"
evaluate:
  results_dir: "${results_dir}/evaluate"
  checkpoint: "???"
  output_sampled_matches_plot: "???"
  output_cmc_curve_plot: "???"
  test_dataset: "???"
  query_dataset: "???"
export:
  results_dir: "${results_dir}/export"
  checkpoint: "???"
