encryption_key: tlt_encode
task: segment
train:
  resume_training_checkpoint_path: null
  segment:
    loss: "ce"
    weights: [0.5, 0.5, 0.5, 0.8, 1.0]
  num_epochs: 1
  num_nodes: 1
  validation_interval: 1
  checkpoint_interval: 1
  optim:
    lr: 0.0002
    optim: "adamw"
    policy: "linear" 
    momentum: 0.9
    weight_decay: 0.01
results_dir: "/results"
model:
  backbone:
    type: "vit_large_nvdinov2"
    pretrained_backbone_path: null
    freeze_backbone: False
  decode_head:
    feature_strides: [4, 8, 16, 32]
dataset:
  segment:
    dataset: "CNDataset"
    root_dir: /data/LEVIR-CD-256-subset
    data_name: "LEVIR-CD"
    label_transform: "norm"
    batch_size: 2
    workers: 2
    multi_scale_train: True
    multi_scale_infer: False
    num_classes: 2
    img_size: 256
    image_folder_name: "A"
    change_image_folder_name: 'B'
    list_folder_name: 'list'
    annotation_folder_name: "label"
    train_split: "train"
    validation_split: "val"
    test_split: 'test'
    predict_split: 'test'
    label_suffix: .png
    augmentation: 
      random_flip:
        vflip_probability: 0.5
        hflip_probability: 0.5
        enable: True
      random_rotate:
        rotate_probability: 0.5
        angle_list: [90, 180, 270]
        enable: True
      random_color:
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
        hue: 0.3
        enable: True
      with_scale_random_crop:
        enable: True
      with_random_crop: True
      with_random_blur: True
evaluate: 
  results_dir: "${results_dir}/evaluate"
  checkpoint: "${results_dir}/train/changenet.pth"
  trt_engine: "${gen_trt_engine.trt_engine}"
  batch_size: ${dataset.segment.batch_size}
  vis_after_n_batches: 1
inference:
  results_dir: "${results_dir}/inference"
  checkpoint: "${results_dir}/train/changenet.pth"
  trt_engine: "${gen_trt_engine.trt_engine}"
  batch_size: ${dataset.segment.batch_size}
  vis_after_n_batches: 1
export:
  results_dir: "${results_dir}/export"
  gpu_id: 0
  checkpoint: "${results_dir}/train/changenet.pth"
  onnx_file: "${export.results_dir}/changenet.onnx"
  input_width: 256
  input_height: 256
  batch_size: ${dataset.segment.batch_size}
gen_trt_engine:
  results_dir: "${results_dir}/gen_trt_engine"
  gpu_id: 0
  onnx_file: "${export.onnx_file}"
  trt_engine: "${gen_trt_engine.results_dir}/changenet.trt"
  batch_size: ${dataset.segment.batch_size}
  input_channel: 3
  input_width: 256
  input_height: 256
  tensorrt:
    data_type: FP32
    workspace_size: 1024
    min_batch_size: 1
    opt_batch_size: 10
    max_batch_size: 10