results_dir: "???"
model:
  backbone: resnet_101
  input_width: 224
  input_height: 224 
  feat_dim: 2048
dataset:
  workers: 8
  val_dataset:
    reference: "???"
    query: "???"
evaluate:
  batch_size: 16
  results_dir: "???"
