model:
  backbone: resnet_50
  input_width: 224
  input_height: 224
  feat_dim: 256
export:
  checkpoint: "???"
  onnx_file: "???"
  results_dir: "???"
  batch_size: -1
  on_cpu: false
  verbose: true
results_dir: "???"